apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: ClusterIP # Change to NodePort or LoadBalancer for external access
  selector:
    app: kafka
  ports:
    - name: kafka-9092
      port: 9092
      targetPort: 9092
    - name: kafka-9093
      port: 9093
      targetPort: 9093 